### ISSUE TITLE
Clirr is not compatible with SonarQube 6.0

### ISSUE THREAD

**Issue by amedee** [SonarCommunity/sonar-clirr#4]
Clirr 1.3 installed in SonarQube 6.0.

Running an analysis gives this error:

```
Caused by: java.lang.NoSuchMethodError: org.sonar.plugins.java.api.JavaResourceLocator.findResourceByClassName(Ljava/lang/String;)Lorg/sonar/api/resources/Resource;
    at org.sonar.plugins.clirr.ClirrSensor.saveIssues(ClirrSensor.java:94)
    at org.sonar.plugins.clirr.ClirrSensor.analyse(ClirrSensor.java:76)
```

Full error at http://stackoverflow.com/questions/39849825/sonarqube-6-0-analysis-fails-on-module-without-code

**Comment by henryju** [comment]
This is an incompatibility with the Java plugin. No (direct) relation with SonarQube 6.0.

**Comment by amedee** [comment]
1. Does that make this issue a duplicate of #3 ?
2. The code base of the Clirr plugin isn't too big, how easy/hard would it be if I would attempt to solve it myself and submit a pull request? No idea where to start, I know Java but I never did any "real" Java development.

**Comment by henryju** [comment]
Indeed, that's a duplicate so let's close this issue and continue discussion on #3. This plugin is no more maintained by SonarSource so you can provide a fix. I don't know how hard it is.
